site_name: Guionardo's Knowledge Base

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      python: fontawesome/brands/python
      go: fontawesome/brands/golang
  features:
    - header.autohide
    - announce.dismiss
    - content.tabs.link

plugins:
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
  - search

extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    Python: python
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/guionardo
    - icon: fontawesome/brands/github
      link: https://github.com/guionardo
  analytics:
    provider: google
    property: G-XP7VGCD38K

repo_url: https://github.com/guionardo/kb

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
