name: MkDocs Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x      
      - name: Install requirements
        run: |          
          pip install -r requirements.txt
      - name: Update last changed
        run: |
          python3 .github/scripts/last_changed.py
      - name: Build and deploy
        working-directory: .
        run: mkdocs gh-deploy --force --clean --verbose
